#!/bin/bash

set -e

SHA1=`git rev-parse --short HEAD | tr -d "\n"`

DEPLOY_FILE=$SHA1.zip

sed "s/<TAG>/${SHA1}/" < Dockerrun.aws.json.template > Dockerrun.aws.json
zip -r $DEPLOY_FILE Dockerrun.aws.json

aws s3 cp $DEPLOY_FILE s3://macropod-deploy/gitr-client/$DEPLOY_FILE

aws elasticbeanstalk create-application-version --application-name Gitr-client --version-label $SHA1 --source-bundle S3Bucket=macropod-deploy,S3Key=pouch/$DEPLOY_FILE  || /bin/true #don't fail if rebuilding

# # Update Elastic Beanstalk environment to new version
aws elasticbeanstalk update-environment --environment-name gitr-client --version-label ${SHA1}